/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoempresa;

import java.awt.Image;
import java.util.ResourceBundle;
import javax.swing.ImageIcon;

/**
 *Desarrolladores:Luis Alberto Garcia Orozco, Juan Pablo Flores Rivera, Oscar Uriel MOrales Peralta
 *Fecha de entrega:!5/05/2019
 *Nombre del programa:TrueProgram (consulta de registros)
 */
public class bienvenido extends javax.swing.JFrame {

    public bienvenido() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setAlwaysOnTop(true);
        cambiar(principal.lenguaje());
        Image icon = new ImageIcon(getClass().getResource("/Imagen/LogoBien.png")).getImage();
        setIconImage(icon);
    }

    public void cambiar(String dir) {
        //cambia de idioma
        ResourceBundle obj = ResourceBundle.getBundle(dir);
        Mensaje.setText(obj.getString("presiona"));
        MensajeBienvenida.setText(obj.getString("bienvenido") + " " + principal.usuario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MensajeBienvenida = new javax.swing.JLabel();
        Mensaje = new javax.swing.JLabel();
        Usuario = new javax.swing.JLabel();
        imagenFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MensajeBienvenida.setBackground(new java.awt.Color(51, 51, 51));
        MensajeBienvenida.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(MensajeBienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 210, 70));

        Mensaje.setForeground(new java.awt.Color(255, 255, 255));
        Mensaje.setText("Presione culaquier tecla para continuar ");
        getContentPane().add(Mensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 320, 40));

        Usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/LogoBien.png"))); // NOI18N
        getContentPane().add(Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 80, 70));

        imagenFondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagenFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/fondoFlecha.jpg"))); // NOI18N
        getContentPane().add(imagenFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 144));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
       //cierra la ventana y abre el menu de busqueda
        dispose();
        menuDeBusqueda menuDeBusqueda = new menuDeBusqueda();
        menuDeBusqueda.setVisible(true);
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bienvenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new bienvenido().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Mensaje;
    private javax.swing.JLabel MensajeBienvenida;
    private javax.swing.JLabel Usuario;
    private javax.swing.JLabel imagenFondo;
    // End of variables declaration//GEN-END:variables
}
