package proyectoempresa;

import java.awt.Desktop;
import java.awt.Image;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.net.URISyntaxException;
import java.util.ResourceBundle;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *Desarrolladores:Luis Alberto Garcia Orozco, Juan Pablo Flores Rivera, Oscar Uriel MOrales Peralta
 *Fecha de entrega:!5/05/2019
 *Nombre del programa:TrueProgram (consulta de registros)
 */
public class eliminar extends javax.swing.JFrame {

    /**
     * Creates new form eliminar
     */
    DefaultTableModel modelo;
    String errorAdmin;
    String errorNoSeleccionado;
    String data[][] = {};
    String tituloParaGuardar = "Usuarios";
    long punteroI = 0, punteroF = 0;
    String usuarioABorrar = "";
    String errorPrivilegios;
    String[] titulo = {tituloParaGuardar};

    public eliminar() {
        //carga todos los elementos
        initComponents();
        cambiarIdioma(principal.lenguaje());
        this.setLocationRelativeTo(null);
        Image icon = new ImageIcon(getClass().getResource("/Imagen/LogoBien.png")).getImage();
        setIconImage(icon);
        //crea un modelo para la tabla
        modelo = new DefaultTableModel(data, titulo);
        //asigan el modelo
        usuarioDato.setModel(modelo);
        leer();
    }

    public void leer() {
        try {
            //lee todos los usuarios para colocarlos
            this.data = new String[][]{};
            modelo = new DefaultTableModel(data, titulo);
            //asigan el modelo
            usuarioDato.setModel(modelo);
            RandomAccessFile usuarios = new RandomAccessFile("users.dat", "r");
            usuarios.seek(0);
            StringBuilder usuario = new StringBuilder();
            char cadena;
            while (usuarios.getFilePointer() <= usuarios.length()) {
                while ((cadena = (char) usuarios.readByte()) != ',') {
                    usuario.append(cadena);
                }
                while ((usuarios.readByte()) != '|') {
                }
                while ((usuarios.readByte()) != '|') {
                }
                String datos[] = {usuario.toString()};
                //agreaga un renglon a la tabla
                modelo.addRow(datos);
                usuario.delete(0, usuario.length());
            }
        } catch (IOException e) {

        }
    }

    public void cambiarIdioma(String dir) {
        //cambia el idioma
        ResourceBundle idioma = ResourceBundle.getBundle(dir);
        errorPrivilegios = idioma.getString("errorprivilegios");
        ingles.setText(idioma.getString("Ingles"));
        idiomaM.setText(idioma.getString("Idioma"));
        aleman.setText(idioma.getString("Aleman"));
        chino.setText(idioma.getString("Chino"));
        ayuda.setText(idioma.getString("ayuda"));
        paginaDeSoporte.setText(idioma.getString("pagina"));
        numeroDeTelefono.setText(idioma.getString("numero"));
        eliminar.setText(idioma.getString("Aceptar"));
        volver.setText(idioma.getString("volver"));
        tituloParaGuardar = idioma.getString("Usuarios");
        titulo[0] = idioma.getString("Usuarios");
        español.setText(idioma.getString("Espanol"));
        errorAdmin = idioma.getString("adiministrador");
        errorNoSeleccionado = idioma.getString("noelimino");
        modelo = new DefaultTableModel(data, titulo);
        usuarioDato.setModel(modelo);
        leer();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usuario = new javax.swing.JScrollPane();
        usuarioDato = new javax.swing.JTable();
        eliminar = new javax.swing.JButton();
        volver = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();
        menu = new javax.swing.JMenuBar();
        idiomaM = new javax.swing.JMenu();
        español = new javax.swing.JMenuItem();
        ingles = new javax.swing.JMenuItem();
        aleman = new javax.swing.JMenuItem();
        chino = new javax.swing.JMenuItem();
        ayuda = new javax.swing.JMenu();
        paginaDeSoporte = new javax.swing.JMenuItem();
        numeroDeTelefono = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TrueProgram    "+"("+principal.usuario+")");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usuario.setBackground(new java.awt.Color(0, 0, 0));
        usuario.setForeground(new java.awt.Color(255, 255, 255));

        usuarioDato.setBackground(new java.awt.Color(0, 0, 0));
        usuarioDato.setForeground(new java.awt.Color(255, 255, 255));
        usuarioDato.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Usuario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        usuarioDato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usuarioDatoMouseClicked(evt);
            }
        });
        usuario.setViewportView(usuarioDato);
        if (usuarioDato.getColumnModel().getColumnCount() > 0) {
            usuarioDato.getColumnModel().getColumn(0).setResizable(false);
        }

        getContentPane().add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 380, 130));

        eliminar.setBackground(new java.awt.Color(51, 51, 51));
        eliminar.setForeground(new java.awt.Color(255, 255, 255));
        eliminar.setText("Eliminar");
        eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                eliminarMousePressed(evt);
            }
        });
        getContentPane().add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 90, 30));

        volver.setBackground(new java.awt.Color(51, 51, 51));
        volver.setForeground(new java.awt.Color(255, 255, 255));
        volver.setText("Volver");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        getContentPane().add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 90, 30));

        fondo.setBackground(new java.awt.Color(51, 51, 255));
        fondo.setForeground(new java.awt.Color(255, 255, 255));
        fondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/fondoFlecha.jpg"))); // NOI18N
        fondo.setFocusable(false);
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 390));

        menu.setBackground(new java.awt.Color(0, 0, 0));
        menu.setBorder(null);
        menu.setForeground(new java.awt.Color(255, 255, 255));

        idiomaM.setForeground(new java.awt.Color(255, 255, 255));
        idiomaM.setText("Idioma");

        español.setBackground(new java.awt.Color(0, 0, 0));
        español.setForeground(new java.awt.Color(255, 255, 255));
        español.setText("Español");
        español.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                españolActionPerformed(evt);
            }
        });
        idiomaM.add(español);

        ingles.setBackground(new java.awt.Color(0, 0, 0));
        ingles.setForeground(new java.awt.Color(255, 255, 255));
        ingles.setText("Inglés");
        ingles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inglesActionPerformed(evt);
            }
        });
        idiomaM.add(ingles);

        aleman.setBackground(new java.awt.Color(0, 0, 0));
        aleman.setForeground(new java.awt.Color(255, 255, 255));
        aleman.setText("Aleman");
        aleman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alemanActionPerformed(evt);
            }
        });
        idiomaM.add(aleman);

        chino.setBackground(new java.awt.Color(0, 0, 0));
        chino.setForeground(new java.awt.Color(255, 255, 255));
        chino.setText("Chino");
        chino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chinoActionPerformed(evt);
            }
        });
        idiomaM.add(chino);

        menu.add(idiomaM);

        ayuda.setBackground(new java.awt.Color(0, 0, 0));
        ayuda.setForeground(new java.awt.Color(255, 255, 255));
        ayuda.setText("Ayuda");

        paginaDeSoporte.setBackground(new java.awt.Color(0, 0, 0));
        paginaDeSoporte.setForeground(new java.awt.Color(255, 255, 255));
        paginaDeSoporte.setText("Pagina de soporte");
        paginaDeSoporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paginaDeSoporteActionPerformed(evt);
            }
        });
        ayuda.add(paginaDeSoporte);

        numeroDeTelefono.setBackground(new java.awt.Color(0, 0, 0));
        numeroDeTelefono.setForeground(new java.awt.Color(255, 255, 255));
        numeroDeTelefono.setText("Numero de soporte");
        numeroDeTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroDeTelefonoActionPerformed(evt);
            }
        });
        ayuda.add(numeroDeTelefono);

        menu.add(ayuda);

        setJMenuBar(menu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void españolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_españolActionPerformed
        //cambia el idioma a español
        cambiarIdioma("Propiedades/Espanol");
        principal.auxIdioma = 1;
    }//GEN-LAST:event_españolActionPerformed

    private void inglesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inglesActionPerformed
        //cambia el idioma a ingles
        cambiarIdioma("Propiedades/Ingles");
        principal.auxIdioma = 2;
    }//GEN-LAST:event_inglesActionPerformed

    private void alemanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alemanActionPerformed
        //cambia el idioma a aleman
        cambiarIdioma("Propiedades/Aleman");
        principal.auxIdioma = 3;
    }//GEN-LAST:event_alemanActionPerformed

    private void chinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chinoActionPerformed
        //cambia el idioma a chino
        cambiarIdioma("Propiedades/Chino");
        principal.auxIdioma = 4;
    }//GEN-LAST:event_chinoActionPerformed

    private void paginaDeSoporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paginaDeSoporteActionPerformed
        try {
            //crea un objeto de tipo URI
            java.net.URI uri = new java.net.URI("https://riverajuanpablo230.wixsite.com/trueprogram");
            //abre la URI
            Desktop.getDesktop().browse(uri);
        } catch (URISyntaxException | IOException or) {
            System.out.println("Error En boton facebook");
        }
    }//GEN-LAST:event_paginaDeSoporteActionPerformed

    private void numeroDeTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroDeTelefonoActionPerformed
        //crea un icono para ser utilizado en el programa
        Icon icon = new ImageIcon(getClass().getResource("/Imagen/LogoBien.png"));
        JOptionPane.showMessageDialog(null, "Pablo: 332-188-2398\n"
                + "Oscar: 348-119-3821\n"
                + "Luis: 392-127-1791", "TrueProgram", 0, icon);
    }//GEN-LAST:event_numeroDeTelefonoActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        menuDeBusqueda obj = new menuDeBusqueda();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_volverActionPerformed
    String usuarioAdmin = "";
    String nombre = "";
    private void usuarioDatoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuarioDatoMouseClicked
        boolean encontrado = false;
        punteroI = 0;
        punteroF = 0;
        //lee el renglon seleccionado por el usuario
        nombre = (String) modelo.getValueAt(usuarioDato.getSelectedRow(), 0);
        char cadena;
        StringBuilder usuarioAConparar = new StringBuilder();
        try {
            RandomAccessFile usuarioArch = new RandomAccessFile("users.dat", "rw");
            usuarioArch.seek(0);
            while (usuarioArch.getFilePointer() <= usuarioArch.length() && (encontrado == false)) {
                //guarda la posicion del puntero
                punteroI = usuarioArch.getFilePointer();
                //lee el usuario
                while ((cadena = (char) usuarioArch.readByte()) != ',') {
                    usuarioAConparar.append(cadena);
                }
                //brinca la contraseña
                while ((usuarioArch.readByte()) != '|') {
                }
                //brinca la direccion de la foto
                while ((usuarioArch.readByte()) != '|') {
                }
                //guarda la posicion del puntero
                punteroF = usuarioArch.getFilePointer();
                if (nombre.equalsIgnoreCase(usuarioAConparar.toString())) {
                    encontrado = true;
                    usuarioABorrar = usuarioAConparar.toString();
                }
                usuarioAConparar.delete(0, usuarioAConparar.length());
            }
        } catch (IOException io) {

        }
    }//GEN-LAST:event_usuarioDatoMouseClicked

    private void eliminarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarMousePressed
        try {
            if (!usuarioABorrar.equals("")) {
                if (!principal.admin.equalsIgnoreCase(usuarioABorrar)) {
                    RandomAccessFile usuarioArch = new RandomAccessFile("users.dat", "rw");
                    long longitud = (usuarioArch.length()) - (punteroF - punteroI);
                    String cadenaU = "";
                    usuarioArch.seek(punteroF);
                    if (usuarioArch.getFilePointer() != usuarioArch.length()) {
                        cadenaU = usuarioArch.readLine();
                    }
                    usuarioArch.seek(punteroI);
                    usuarioArch.setLength(longitud);
                    usuarioArch.writeBytes(cadenaU);
                    leer();
                } else {
                    JOptionPane.showMessageDialog(null, errorAdmin, "TrueProgram", 0, null);
                }
            } else {
                JOptionPane.showMessageDialog(null, errorNoSeleccionado, "TrueProgram", 0, null);
            }

        } catch (IOException io) {

        }
    }//GEN-LAST:event_eliminarMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(eliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(eliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(eliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(eliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new eliminar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aleman;
    private javax.swing.JMenu ayuda;
    private javax.swing.JMenuItem chino;
    private javax.swing.JButton eliminar;
    private javax.swing.JMenuItem español;
    private javax.swing.JLabel fondo;
    private javax.swing.JMenu idiomaM;
    private javax.swing.JMenuItem ingles;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenuItem numeroDeTelefono;
    private javax.swing.JMenuItem paginaDeSoporte;
    private javax.swing.JScrollPane usuario;
    private javax.swing.JTable usuarioDato;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
