/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoempresa;

import java.awt.Color;
import java.awt.Desktop;
import java.awt.Image;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.net.URISyntaxException;
import java.util.ResourceBundle;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;

/**
 * Desarrolladores:Luis Alberto Garcia Orozco, Juan Pablo Flores Rivera, Osca Uriel MOrales Peralta 
 * Fecha de entrega:!5/05/2019 Nombre del
 * programa:TrueProgram (consulta de registros)
 */
public class fotosDePerfil extends javax.swing.JFrame {

    /**
     * Creates new form fotosDePerfil
     */
    public fotosDePerfil() {
        initComponents();
        cambiarIdioma(principal.lenguaje());
        this.setLocationRelativeTo(null);
        Image icon = new ImageIcon(getClass().getResource("/Imagen/LogoBien.png")).getImage();
        setIconImage(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Imagen2 = new javax.swing.JLabel();
        Imagen1 = new javax.swing.JLabel();
        Imagen3 = new javax.swing.JLabel();
        Imagen4 = new javax.swing.JLabel();
        Imagen5 = new javax.swing.JLabel();
        Imagen6 = new javax.swing.JLabel();
        Volver = new javax.swing.JButton();
        Aceptar = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();
        Menu = new javax.swing.JMenuBar();
        Idioma = new javax.swing.JMenu();
        Español = new javax.swing.JMenuItem();
        Ingles = new javax.swing.JMenuItem();
        Aleman = new javax.swing.JMenuItem();
        Chino = new javax.swing.JMenuItem();
        ayuda = new javax.swing.JMenu();
        PaguinaDeSoporte = new javax.swing.JMenuItem();
        NumeroDeTelefono = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TrueProgram    "+"("+principal.usuario+")");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Imagen2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/hombre2.png"))); // NOI18N
        Imagen2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Imagen2MousePressed(evt);
            }
        });
        getContentPane().add(Imagen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 130, 130));

        Imagen1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/default.png"))); // NOI18N
        Imagen1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Imagen1MousePressed(evt);
            }
        });
        getContentPane().add(Imagen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 130, 130));

        Imagen3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/hombre1.png"))); // NOI18N
        Imagen3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Imagen3MousePressed(evt);
            }
        });
        getContentPane().add(Imagen3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 130, 130));

        Imagen4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/chica2.png"))); // NOI18N
        Imagen4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Imagen4MousePressed(evt);
            }
        });
        getContentPane().add(Imagen4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 130, 130));

        Imagen5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/chica1.png"))); // NOI18N
        Imagen5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Imagen5MousePressed(evt);
            }
        });
        getContentPane().add(Imagen5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 130, 130));

        Imagen6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/hombre3.png"))); // NOI18N
        Imagen6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Imagen6MousePressed(evt);
            }
        });
        getContentPane().add(Imagen6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 130, 130));

        Volver.setBackground(new java.awt.Color(51, 51, 51));
        Volver.setForeground(new java.awt.Color(255, 255, 255));
        Volver.setText("jButton1");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });
        getContentPane().add(Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 120, 40));

        Aceptar.setBackground(new java.awt.Color(51, 51, 51));
        Aceptar.setForeground(new java.awt.Color(255, 255, 255));
        Aceptar.setText("jButton1");
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });
        getContentPane().add(Aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, 120, 40));

        Fondo.setBackground(new java.awt.Color(51, 51, 255));
        Fondo.setForeground(new java.awt.Color(255, 255, 255));
        Fondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/fondoFlecha.jpg"))); // NOI18N
        Fondo.setFocusable(false);
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 440));

        Menu.setBackground(new java.awt.Color(0, 0, 0));
        Menu.setBorder(null);
        Menu.setForeground(new java.awt.Color(255, 255, 255));

        Idioma.setBackground(new java.awt.Color(0, 0, 0));
        Idioma.setForeground(new java.awt.Color(255, 255, 255));
        Idioma.setText("Idioma");

        Español.setBackground(new java.awt.Color(0, 0, 0));
        Español.setForeground(new java.awt.Color(255, 255, 255));
        Español.setText("Español");
        Español.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EspañolActionPerformed(evt);
            }
        });
        Idioma.add(Español);

        Ingles.setBackground(new java.awt.Color(0, 0, 0));
        Ingles.setForeground(new java.awt.Color(255, 255, 255));
        Ingles.setText("Inglés");
        Ingles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InglesActionPerformed(evt);
            }
        });
        Idioma.add(Ingles);

        Aleman.setBackground(new java.awt.Color(0, 0, 0));
        Aleman.setForeground(new java.awt.Color(255, 255, 255));
        Aleman.setText("Aleman");
        Aleman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlemanActionPerformed(evt);
            }
        });
        Idioma.add(Aleman);

        Chino.setBackground(new java.awt.Color(0, 0, 0));
        Chino.setForeground(new java.awt.Color(255, 255, 255));
        Chino.setText("Chino");
        Chino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChinoActionPerformed(evt);
            }
        });
        Idioma.add(Chino);

        Menu.add(Idioma);

        ayuda.setBackground(new java.awt.Color(0, 0, 0));
        ayuda.setForeground(new java.awt.Color(255, 255, 255));
        ayuda.setText("Ayuda");

        PaguinaDeSoporte.setBackground(new java.awt.Color(0, 0, 0));
        PaguinaDeSoporte.setForeground(new java.awt.Color(255, 255, 255));
        PaguinaDeSoporte.setText("Pagina de soporte");
        PaguinaDeSoporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaguinaDeSoporteActionPerformed(evt);
            }
        });
        ayuda.add(PaguinaDeSoporte);

        NumeroDeTelefono.setBackground(new java.awt.Color(0, 0, 0));
        NumeroDeTelefono.setForeground(new java.awt.Color(255, 255, 255));
        NumeroDeTelefono.setText("Numero de soporte");
        NumeroDeTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumeroDeTelefonoActionPerformed(evt);
            }
        });
        ayuda.add(NumeroDeTelefono);

        Menu.add(ayuda);

        setJMenuBar(Menu);

        pack();
    }// </editor-fold>//GEN-END:initComponents
  public void cambiarIdioma(String dir) {
        //cambia el idioma
        ResourceBundle obj = ResourceBundle.getBundle(dir);
        Volver.setText(obj.getString("volver"));
        Aceptar.setText(obj.getString("Aceptar"));
        Aceptado = obj.getString("aceptado");
        advertencia = obj.getString("falloImagen");
        Idioma.setText(obj.getString("Idioma"));
        ayuda.setText(obj.getString("ayuda"));
        PaguinaDeSoporte.setText(obj.getString("pagina"));
        NumeroDeTelefono.setText(obj.getString("numero"));
        Español.setText(obj.getString("Espanol"));
        Ingles.setText(obj.getString("Ingles"));
        Aleman.setText(obj.getString("Aleman"));
        Chino.setText(obj.getString("Chino"));
    }
    private void EspañolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EspañolActionPerformed
        //cambia el idioma a español
        cambiarIdioma("Propiedades/Espanol");
        principal.auxIdioma = 1;
    }//GEN-LAST:event_EspañolActionPerformed

    private void InglesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InglesActionPerformed
        cambiarIdioma("Propiedades/Ingles");
        principal.auxIdioma = 2;
    }//GEN-LAST:event_InglesActionPerformed

    private void AlemanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlemanActionPerformed
        cambiarIdioma("Propiedades/Aleman");
        principal.auxIdioma = 3;
    }//GEN-LAST:event_AlemanActionPerformed

    private void ChinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChinoActionPerformed
        cambiarIdioma("Propiedades/Chino");
        principal.auxIdioma = 4;
    }//GEN-LAST:event_ChinoActionPerformed

    private void PaguinaDeSoporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaguinaDeSoporteActionPerformed
        try {
            java.net.URI uri = new java.net.URI("https://riverajuanpablo230.wixsite.com/trueprogram");
            Desktop.getDesktop().browse(uri);
        } catch (URISyntaxException | IOException or) {
            System.out.println("Error En boton facebook");
        }
    }//GEN-LAST:event_PaguinaDeSoporteActionPerformed

    Icon icon = new ImageIcon(getClass().getResource("/Imagen/LogoBien.png"));
    private void NumeroDeTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumeroDeTelefonoActionPerformed
        JOptionPane.showMessageDialog(null, "Pablo: 332-188-2398\n"
                + "Oscar: 348-119-3821\n"
                + "Luis: 392-127-1791", "TrueProgram", 0, icon);
    }//GEN-LAST:event_NumeroDeTelefonoActionPerformed

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        menuDeBusqueda obj = new menuDeBusqueda();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_VolverActionPerformed
    String dir = "";
    int imagen;
    private void Imagen1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Imagen1MousePressed
        imagen = 1;
        seleccionarImagen();
    }//GEN-LAST:event_Imagen1MousePressed

    private void Imagen3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Imagen3MousePressed
        imagen = 3;
        seleccionarImagen();
    }//GEN-LAST:event_Imagen3MousePressed

    private void Imagen2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Imagen2MousePressed
        imagen = 2;
        seleccionarImagen();
    }//GEN-LAST:event_Imagen2MousePressed

    private void Imagen6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Imagen6MousePressed
        imagen = 6;
        seleccionarImagen();
    }//GEN-LAST:event_Imagen6MousePressed

    private void Imagen5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Imagen5MousePressed
        imagen = 5;
        seleccionarImagen();
    }//GEN-LAST:event_Imagen5MousePressed

    private void Imagen4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Imagen4MousePressed
        imagen = 4;
        seleccionarImagen();
    }//GEN-LAST:event_Imagen4MousePressed
    public void seleccionarImagen() {
        Border borde = new LineBorder(Color.white, 4);
        switch (imagen) {
            case 1:
                dir = "/Imagen/default.png";
                Imagen1.setBorder(borde);
                Imagen2.setBorder(null);
                Imagen3.setBorder(null);
                Imagen4.setBorder(null);
                Imagen5.setBorder(null);
                Imagen6.setBorder(null);
                break;
            case 2:
                dir = "/Imagen/hombre2.png";
                Imagen2.setBorder(borde);
                Imagen1.setBorder(null);
                Imagen3.setBorder(null);
                Imagen4.setBorder(null);
                Imagen5.setBorder(null);
                Imagen6.setBorder(null);
                break;
            case 3:
                dir = "/Imagen/hombre1.png";
                Imagen3.setBorder(borde);
                Imagen2.setBorder(null);
                Imagen1.setBorder(null);
                Imagen4.setBorder(null);
                Imagen5.setBorder(null);
                Imagen6.setBorder(null);
                break;
            case 4:
                dir = "/Imagen/chica2.png";
                Imagen4.setBorder(borde);
                Imagen2.setBorder(null);
                Imagen3.setBorder(null);
                Imagen1.setBorder(null);
                Imagen5.setBorder(null);
                Imagen6.setBorder(null);
                break;
            case 5:
                dir = "/Imagen/chica1.png";
                Imagen5.setBorder(borde);
                Imagen2.setBorder(null);
                Imagen3.setBorder(null);
                Imagen4.setBorder(null);
                Imagen1.setBorder(null);
                Imagen6.setBorder(null);
                break;
            case 6:
                dir = "/Imagen/hombre3.png";
                Imagen6.setBorder(borde);
                Imagen2.setBorder(null);
                Imagen3.setBorder(null);
                Imagen4.setBorder(null);
                Imagen5.setBorder(null);
                Imagen1.setBorder(null);
                break;
        }
    }
    String advertencia;
    String Aceptado;
    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
        try {
            if (dir.isEmpty()) {
                JOptionPane.showMessageDialog(null, advertencia, "TrueProgram", 0, icon);
            } else {
                long posI = menuDeBusqueda.posicion;
                String escribir = "";
                RandomAccessFile users = new RandomAccessFile("users.dat", "rw");
                char caracter;
                users.seek(menuDeBusqueda.posicion);
                while ((caracter = (char) users.readByte()) != '|') {

                }
                if (users.getFilePointer() != users.length()) {
                    escribir = users.readLine();
                }
                users.seek(posI);
                users.writeBytes(dir + "|");
                users.setLength(users.getFilePointer());
                users.writeBytes(escribir);
                JOptionPane.showMessageDialog(null, Aceptado, "TrueProgram", 0, icon);
            }
        } catch (IOException ew) {

        }
    }//GEN-LAST:event_AceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fotosDePerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fotosDePerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fotosDePerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fotosDePerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fotosDePerfil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JMenuItem Aleman;
    private javax.swing.JMenuItem Chino;
    public javax.swing.JMenuItem Español;
    private javax.swing.JLabel Fondo;
    private javax.swing.JMenu Idioma;
    private javax.swing.JLabel Imagen1;
    private javax.swing.JLabel Imagen2;
    private javax.swing.JLabel Imagen3;
    private javax.swing.JLabel Imagen4;
    private javax.swing.JLabel Imagen5;
    private javax.swing.JLabel Imagen6;
    public javax.swing.JMenuItem Ingles;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenuItem NumeroDeTelefono;
    private javax.swing.JMenuItem PaguinaDeSoporte;
    private javax.swing.JButton Volver;
    private javax.swing.JMenu ayuda;
    // End of variables declaration//GEN-END:variables
}
