/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoempresa;

import java.awt.Desktop;
import java.awt.Image;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.net.URISyntaxException;
import java.util.Arrays;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javazoom.jl.decoder.JavaLayerException;
import javazoom.jl.player.Player;

/**
 *Desarrolladores:Luis Alberto Garcia Orozco, Juan Pablo Flores Rivera, Oscar Uriel MOrales Peralta
 *Fecha de entrega:!5/05/2019
 *Nombre del programa:TrueProgram (consulta de registros)
 */
public class pantallaDeRegistro extends javax.swing.JFrame {

    /**
     * Creates new form PantallaDeRegistro
     */
    public pantallaDeRegistro() {
        initComponents();
        Image icon = new ImageIcon(getClass().getResource("/Imagen/LogoBien.png")).getImage();
        setIconImage(icon);
        cambiarIdioma(principal.lenguaje());
        this.setLocationRelativeTo(null);
    }

    public void cambiarIdioma(String dir) {
        //cambia el idioma
        ResourceBundle obj = ResourceBundle.getBundle(dir);
        contraseñaText.setText(obj.getString("Contraseña:"));
        usuariotext.setText(obj.getString("Usuario:"));
        español.setText(obj.getString("Espanol"));
        ingles.setText(obj.getString("Ingles"));
        idioma.setText(obj.getString("Idioma"));
        aleman.setText(obj.getString("Aleman"));
        chino.setText(obj.getString("Chino"));
        ayuda.setText(obj.getString("ayuda"));
        paginaDeSoporte.setText(obj.getString("pagina"));
        numeroDeTelefono.setText(obj.getString("numero"));
        usuarioCreado = obj.getString("UsuarioCreado");
        noCoinciden = obj.getString("ContraseñasNoson");
        usuarioUsado = obj.getString("usuarioinvalido");
        noIngresada = obj.getString("ContraseñaNoIngresada");
        noencontrado = obj.getString("noencontrado");
        confirmarcontra.setText(obj.getString("confiramarcontraseña"));
        aceptar.setText(obj.getString("Aceptar"));
        mensaje.setText(obj.getString("bienvenido"));
        contraseñaInvalida = obj.getString("contraseñainvalida");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usuariotext = new javax.swing.JLabel();
        contraseñaText = new javax.swing.JLabel();
        passwordR1 = new javax.swing.JPasswordField();
        usuario = new javax.swing.JTextField();
        passwordR2 = new javax.swing.JPasswordField();
        confirmarcontra = new javax.swing.JLabel();
        aceptar = new javax.swing.JButton();
        mensaje = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();
        menu = new javax.swing.JMenuBar();
        idioma = new javax.swing.JMenu();
        español = new javax.swing.JMenuItem();
        ingles = new javax.swing.JMenuItem();
        aleman = new javax.swing.JMenuItem();
        chino = new javax.swing.JMenuItem();
        ayuda = new javax.swing.JMenu();
        paginaDeSoporte = new javax.swing.JMenuItem();
        numeroDeTelefono = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TrueProgram");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usuariotext.setForeground(new java.awt.Color(255, 255, 255));
        usuariotext.setText("Usuario :");
        getContentPane().add(usuariotext, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 100, 44));

        contraseñaText.setForeground(new java.awt.Color(255, 255, 255));
        contraseñaText.setText("Contraseña:");
        getContentPane().add(contraseñaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 110, 40));

        passwordR1.setBackground(new java.awt.Color(51, 51, 51));
        passwordR1.setForeground(new java.awt.Color(255, 255, 255));
        passwordR1.setCaretColor(new java.awt.Color(255, 255, 255));
        passwordR1.setSelectionColor(new java.awt.Color(255, 255, 255));
        getContentPane().add(passwordR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 270, 50));

        usuario.setBackground(new java.awt.Color(51, 51, 51));
        usuario.setForeground(new java.awt.Color(255, 255, 255));
        usuario.setCaretColor(new java.awt.Color(255, 255, 255));
        usuario.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        usuario.setSelectionColor(new java.awt.Color(255, 255, 255));
        getContentPane().add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 270, 44));

        passwordR2.setBackground(new java.awt.Color(51, 51, 51));
        passwordR2.setForeground(new java.awt.Color(255, 255, 255));
        passwordR2.setCaretColor(new java.awt.Color(255, 255, 255));
        passwordR2.setSelectedTextColor(new java.awt.Color(0, 0, 102));
        passwordR2.setSelectionColor(new java.awt.Color(255, 255, 255));
        getContentPane().add(passwordR2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 270, 50));

        confirmarcontra.setForeground(new java.awt.Color(255, 255, 255));
        confirmarcontra.setText("Confirmar contraseña:");
        getContentPane().add(confirmarcontra, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 120, 50));

        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });
        getContentPane().add(aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, 90, 30));

        mensaje.setForeground(new java.awt.Color(255, 255, 255));
        mensaje.setText("jLabel1");
        getContentPane().add(mensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 270, 50));

        fondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/fondoFlecha.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 310));

        menu.setBackground(new java.awt.Color(0, 0, 0));
        menu.setBorder(null);
        menu.setForeground(new java.awt.Color(255, 255, 255));

        idioma.setForeground(new java.awt.Color(255, 255, 255));
        idioma.setText("Idioma");

        español.setBackground(new java.awt.Color(0, 0, 0));
        español.setForeground(new java.awt.Color(255, 255, 255));
        español.setText("Español");
        español.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                españolActionPerformed(evt);
            }
        });
        idioma.add(español);

        ingles.setBackground(new java.awt.Color(0, 0, 0));
        ingles.setForeground(new java.awt.Color(255, 255, 255));
        ingles.setText("Inglés");
        ingles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inglesActionPerformed(evt);
            }
        });
        idioma.add(ingles);

        aleman.setBackground(new java.awt.Color(0, 0, 0));
        aleman.setForeground(new java.awt.Color(255, 255, 255));
        aleman.setText("Aleman");
        aleman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alemanActionPerformed(evt);
            }
        });
        idioma.add(aleman);

        chino.setBackground(new java.awt.Color(0, 0, 0));
        chino.setForeground(new java.awt.Color(255, 255, 255));
        chino.setText("Chino");
        chino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chinoActionPerformed(evt);
            }
        });
        idioma.add(chino);

        menu.add(idioma);

        ayuda.setBackground(new java.awt.Color(0, 0, 0));
        ayuda.setForeground(new java.awt.Color(255, 255, 255));
        ayuda.setText("Ayuda");

        paginaDeSoporte.setBackground(new java.awt.Color(0, 0, 0));
        paginaDeSoporte.setForeground(new java.awt.Color(255, 255, 255));
        paginaDeSoporte.setText("Pagina de soporte");
        paginaDeSoporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paginaDeSoporteActionPerformed(evt);
            }
        });
        ayuda.add(paginaDeSoporte);

        numeroDeTelefono.setBackground(new java.awt.Color(0, 0, 0));
        numeroDeTelefono.setForeground(new java.awt.Color(255, 255, 255));
        numeroDeTelefono.setText("Numero de soporte");
        numeroDeTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroDeTelefonoActionPerformed(evt);
            }
        });
        ayuda.add(numeroDeTelefono);

        menu.add(ayuda);

        setJMenuBar(menu);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    String usuarioCreado;
    String noCoinciden;
    String usuarioUsado;
    String noIngresada;
    String noencontrado;
    String contraseñaInvalida;

    private void españolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_españolActionPerformed
        //cambia el idioma a español
        cambiarIdioma("Propiedades/Espanol");
        principal.auxIdioma = 1;
    }//GEN-LAST:event_españolActionPerformed

    private void inglesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inglesActionPerformed
        //cambia el idioma a ingles
        cambiarIdioma("Propiedades/Ingles");
        principal.auxIdioma = 2;
    }//GEN-LAST:event_inglesActionPerformed

    private void alemanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alemanActionPerformed
        //cambia el idioma a aleman
        cambiarIdioma("Propiedades/Aleman");
        principal.auxIdioma = 3;
    }//GEN-LAST:event_alemanActionPerformed

    private void chinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chinoActionPerformed
        //cambia el idioma a chino
        cambiarIdioma("Propiedades/Chino");
        principal.auxIdioma = 4;
    }//GEN-LAST:event_chinoActionPerformed

    private void paginaDeSoporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paginaDeSoporteActionPerformed
        try {
            //crea un objeto de tipo URI
            java.net.URI uri = new java.net.URI("https://riverajuanpablo230.wixsite.com/trueprogram");
            //abre la URI
            Desktop.getDesktop().browse(uri);
        } catch (URISyntaxException | IOException or) {
            System.out.println("Error En boton facebook");
        }
    }//GEN-LAST:event_paginaDeSoporteActionPerformed

    private void numeroDeTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroDeTelefonoActionPerformed
        Icon icon = new ImageIcon(getClass().getResource("/Imagen/LogoBien.png"));
        JOptionPane.showMessageDialog(null, "Pablo: 332-188-2398\n"
                + "Oscar: 348-119-3821\n"
                + "Luis: 392-127-1791", "TrueProgram", 0, icon);
    }//GEN-LAST:event_numeroDeTelefonoActionPerformed
    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        try {
            //crea el administrador
            Player audioError = new Player(new FileInputStream("AudioError.mp3"));
            Icon icon = new ImageIcon(getClass().getResource("/Imagen/LogoBien.png"));
            RandomAccessFile usuarios = new RandomAccessFile("users.dat", "rw");
            //recoge las contraseñas ingresadas
            char[] array = passwordR1.getPassword();
            String password = new String(array);
            char[] arrayComparar = passwordR2.getPassword();
            String passwordComparar = new String(arrayComparar);
            //verifica si el usuario esta vacio o empieza con espacio
            if (!usuario.getText().isEmpty()
                    && !usuario.getText().startsWith(" ")) {
                if (!password.contains(" ")) {
                    if (password.equals(passwordComparar)) {//verifica que las 2 contraseñas sean iguales
                        if (!passwordComparar.equals("") && !passwordComparar.startsWith(" ")) {//verifica que el campo de contraseñas no este vacio
                            //escribe el usuario
                            usuarios.writeBytes(usuario.getText().trim() + ",");
                            //encripta la contraseña
                            String contraseña;
                            contraseña = principal.cifradoCesar(password.trim());
                            //escribe la contraseña y la imagen por default
                            usuarios.writeBytes(contraseña + "|");
                            usuarios.writeBytes("/Imagen/Usuario.png" + "|");
                            usuarios.close();
                            JOptionPane.showMessageDialog(null, usuarioCreado + ":  '" + usuario.getText() + "'", "TrueProgram", 0, icon);
                            //abre la ventana de inicio de sesion
                            principal.leerAdmin();
                            inicioDeSesion ventanaDeInicioDeSesioin = new inicioDeSesion();
                            ventanaDeInicioDeSesioin.setVisible(true);
                            dispose();
                        } else {
                            audioError.play();
                            JOptionPane.showMessageDialog(null, noIngresada, "TrueProgram", 0, null);
                        }
                    } else {
                        audioError.play();
                        JOptionPane.showMessageDialog(null, noCoinciden, "TrueProgram", 0, null);
                    }
                } else {
                    audioError.play();
                    JOptionPane.showMessageDialog(null, contraseñaInvalida, "TrueProgram", 0, null);
                }
            } else {
                audioError.play();
                JOptionPane.showMessageDialog(null, usuarioUsado, "TrueProgram", 0, null);
            }
        } catch (IOException | JavaLayerException oe) {
            Logger.getLogger(pantallaDeRegistro.class.getName()).log(Level.SEVERE, null, oe);
        }
    }//GEN-LAST:event_aceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pantallaDeRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pantallaDeRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pantallaDeRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pantallaDeRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pantallaDeRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JMenuItem aleman;
    private javax.swing.JMenu ayuda;
    private javax.swing.JMenuItem chino;
    private javax.swing.JLabel confirmarcontra;
    private javax.swing.JLabel contraseñaText;
    private javax.swing.JMenuItem español;
    private javax.swing.JLabel fondo;
    private javax.swing.JMenu idioma;
    private javax.swing.JMenuItem ingles;
    private javax.swing.JLabel mensaje;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenuItem numeroDeTelefono;
    private javax.swing.JMenuItem paginaDeSoporte;
    private javax.swing.JPasswordField passwordR1;
    private javax.swing.JPasswordField passwordR2;
    private javax.swing.JTextField usuario;
    private javax.swing.JLabel usuariotext;
    // End of variables declaration//GEN-END:variables
}
